Add sorting for person attributes
AY2324S2-CS2103T-W12-1/tp pull request #93
Opened 2024-03-25 07:54 UTC by solomonng2001

Unable to sort clients by their attributes.

Addition of sort will allow convenient access when looking up clients. Closes #17, #20

Let's
* make person attributes comparable, by implementing the interface.
* Add sorting command and parser.
* Add person comparator to abstract to logic for handling comparators.
* Add tests in model, commands and parser.
* Update ui to refresh client list after every command execute.

2024-03-26 07:11 UTC, ReganChoy commented on src/main/java/seedu/address/model/person/Birthday.java
>      public static final String MESSAGE_CONSTRAINTS = DateUtil.getMessageConstraintsForDateType("Birthday");
Good use of Comparable to help with sorting

2024-03-26 07:13 UTC, ReganChoy commented on src/main/java/seedu/address/model/person/PersonComparator.java
> +package seedu.address.model.person;
Good further abstraction by making another PersonComparator class

2024-03-26 07:14 UTC, ReganChoy commented
Good use of the Comparable interface in all classes to support the sorting command.

2024-03-26 15:13 UTC, yorklim requested changes
Overall LGTM! Just unsure if some of the implementations should be done that way.

2024-03-26 15:13 UTC, yorklim commented on src/main/java/seedu/address/model/ModelManager.java
> +
The sort will cause the filtered list to reset and will return a full sorted list, is it possible to keep sort the already filtered list?

2024-03-26 15:13 UTC, yorklim commented on src/main/java/seedu/address/model/person/PersonComparator.java
> +            return Comparator.comparing(Person::getName);
Shouldn't the default sort return the list unmodified?

2024-03-27 12:32 UTC, yorklim commented on src/main/java/seedu/address/model/person/PriorityValue.java
> +    LOW, MEDIUM, HIGH, VIP; // Order of priority values matters for compareTo method (low < medium < high < vip)
I like that you use an enum class to represent the different values, to ensure that no other incorrect values are taken. Good Job!

2024-03-27 12:32 UTC, yorklim commented on src/main/java/seedu/address/logic/commands/SortCommand.java
> +package seedu.address.logic.commands;
Nice and clean code! Good job with the Javadoc comments as well! Well Written

2024-03-27 12:32 UTC, yorklim commented on src/main/java/seedu/address/model/person/PersonComparator.java
> +package seedu.address.model.person;
Should the comparator be in the person directory? Or can we consider putting it in the model instead, as having the comparator in the person directory seems like the comparator is part of the person.

2024-03-27 15:10 UTC, getsquared approved these changes

2024-03-27 15:10 UTC, getsquared commented on src/main/java/seedu/address/model/person/SortOrder.java
> +public enum SortOrder {
I like that you abstracted out SortCriteria and SortOrder into their own classes!

2024-03-27 15:10 UTC, getsquared commented on src/main/java/seedu/address/ui/MainWindow.java
> +    private void refreshAllPanels() {
Nice thinking to refresh all panels at once, I did not think of that

2024-03-27 15:10 UTC, getsquared commented on src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
> +public class SortCommandParserTest {
Very comprehensive testing done here, keep up the good work 😄

2024-03-27 15:17 UTC, getsquared reviewed
LGTM! 👍

2024-03-27 15:17 UTC, getsquared commented on src/main/java/seedu/address/model/person/SortOrder.java
> +public enum SortOrder {
I like that you abstracted out SortCriteria and SortOrder!

2024-03-27 15:17 UTC, getsquared commented on src/main/java/seedu/address/ui/MainWindow.java
> +    private void refreshAllPanels() {
Great thinking on having a function to refresh all panels at once!

2024-03-27 15:17 UTC, getsquared commented on src/test/java/seedu/address/model/person/SortCriteriaTest.java
> +public class SortCriteriaTest {
Very comprehensive testing done here, keep up the good work 😄

2024-03-27 15:41 UTC, merged